attendance_app/attendance_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from home import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'))),
    path('user/', include(('user.urls', 'user'))),
    path('course/', include(('course.urls', 'course'))),
    path('survey/', include(('survey.urls', 'survey')))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

attendance_app/course/urls.py
from django.urls import path, include
from course import views

from django.contrib.auth import views as auth_views

app_name = 'course'

urlpatterns = [
    path('<int:pk>', views.course_list, name='course_list'),
    path('detail/<int:pk>/', views.course_detail, name='course_detail'),
    

    
    path('create/', views.create_course, name='create_course'),
    path('edit/<int:pk>/', views.edit_course, name='edit_course'),
    path('delete/<int:pk>/', views.delete_course, name='delete_course'),
    path('download/<int:pk>', views.download_attendance, name='download_attendance' ),


    path('attendance_division_list/', views.attendance_divison_list, name='attendance_division_list'),
    path('attendance_course_list/<int:pk>/', views.attendance_course_list, name='attendance_course_list'),
    path('attendance_course_board/<int:pk>/', views.attendance_course_board, name='attendance_course_board'),


    path('QRScanner_in/<int:pk>/', views.QRScanner_in, name='QRScanner_in'),
    path('QRScanner_out/<int:pk>/', views.QRScanner_out, name='QRScanner_out'),
    path('attendance_check_in', views.attendance_check_in, name='attendance_check_in'),
    path('attendance_check_in_success/<int:pk>/', views.attendance_check_in_success, name='attendance_check_in_success'),
    path('attendance_check_out', views.attendance_check_out, name='attendance_check_out'),
    
    path('student_attendance_update', views.student_attendance_update, name='student_attendance_update'),

]

attendance_app/home/urls.py
from django.urls import path, include
from home import views

from django.contrib.auth import views as auth_views
from home.forms import CustomAuthenticationForm


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=CustomAuthenticationForm), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

attendance_app/survey/urls.py
from django.urls import path, include
from survey import views


app_name = 'survey'

urlpatterns = [
    path('', views.survey_division_list, name='survey_division_list'),
    path('course_survey/<int:pk>', views.survey_list, name='survey_list'),
    path('detail/<int:pk>/', views.survey_detail, name='survey_detail'),
    path('reply_detail/<int:pk>/', views.survey_reply_detail, name='survey_reply_detail'),
    
    # 설문 목록 다운로드
    path('download/<int:pk>/', views.download_surveyreply, name='download_surveyreply'),
    
    
    # 학생 설문 페이지 
    path('survey_student_reply/<int:pk>/', views.survey_student_reply, name='survey_student_reply'),
    path('survey_student_submit/', views.survey_student_submit, name='survey_student_submit'),
    
    # path('create/', views.create_course, name='create_course'),
    # path('edit/<int:pk>/', views.edit_course, name='edit_course'),
    # path('delete/<int:pk>/', views.delete_course, name='delete_course'),
]

attendance_app/user/urls.py
# user.urls

from django.urls import path

from user import views

urlpatterns = [
    path('admin_home', views.admin_home, name='admin_home'),

    path('student_detail/', views.student_detail, name='student_detail'),
    path('student_attendance_detail/', views.student_attendance_detail, name='student_attendance_detail'),
    path('edit_student/', views.edit_student, name='edit_student'),
    path('edit_passowrd/', views.edit_password, name='edit_password'),
    path('delete_student/', views.delete_student, name='delete_student'),

    path('signup/', views.signup, name='signup'),
    
    path('show_in_qr/', views.show_in_qr, name='show_in_qr'),
    path('show_out_qr/', views.show_out_qr, name='show_out_qr'),
    
    path('division_list/', views.division_list, name='division_list'),
    path('create_division/', views.create_division, name='create_division'),
    path('edit_division/<int:division_id>/', views.edit_division, name='edit_division'),
    path('delete_division/<int:division_id>/', views.delete_division, name='delete_division'),

]

attendance_app/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.
class Division(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    
class Student(models.Model):
    GENDER_CHOICES = (
        ('M', '남자'),
        ('F', '여자'),
        ('O', '기타'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    birth_date = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    division = models.ForeignKey(Division, on_delete=models.PROTECT)
    qr_code = models.ImageField(upload_to='qr_codes/')

    # 현재 수강중인 강의 추가
    current_course_name = models.CharField(max_length=20, default="수강중인 강의 없음", null=True)

    def __str__(self):
        return self.name

attendance_app/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from user.models import Student, Division
from course.models import ClassAttend, Course
from django.db.models import Q

from django.contrib.auth import login, authenticate

from user.forms import SignUpForm, ClientForm
from django.contrib import messages

from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.db.models import ProtectedError
from django.contrib.auth.hashers import make_password

from django.contrib.auth.hashers import make_password
from django.core.files import File
from pathlib import Path

from io import BytesIO

from user.forms import DivisionForm
from django.contrib.auth import update_session_auth_hash

from user.forms import DivisionForm, StudentEditForm, PasswordChangeFormCustom

from django.contrib.auth.decorators import login_required, user_passes_test

import qrcode, os
# Create your views here.
# 관리자 페이지
@user_passes_test(lambda u: u.is_staff, login_url='/') # 권한 없으면 홈으로
def admin_home(request):
    return render(request, 'user/admin/admin_home.html')


# 학생 계정 추가 
def signup(request):
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)
        client_form = ClientForm(request.POST)
        
        if signup_form.is_valid() and client_form.is_valid():
            # 회원가입 후 자동 로그인
            username = signup_form.cleaned_data.get('username')
            password = signup_form.cleaned_data.get('password')
            password2 = signup_form.cleaned_data.get('password2')

            # 비밀번호가 유효하지않음.
            if password != password2:
                messages.error(request, "비밀번호가 일치하지 않습니다.")
                return render(request, 'user/student/signup.html', {'signup_form': signup_form, 'client_form': client_form})
            
            else:
                try:
                    # 비밀번호 검증
                    validate_password(password)
                    validate_password(password2)
                    
                    # 비밀번호 암호화
                    hashed_password = make_password(password)
                    
                    user = signup_form.save(commit=False)
                    user.password = hashed_password  # 암호화된 비밀번호 설정
                    user.save()
                    
                    student = client_form.save(commit=False)
                    student.user = user

                     # qr코드 생성
                    qr_date = student.name
                    qr = qrcode.QRCode()
                    qr.add_data(qr_date)
                    qr.make()
                    img = qr.make_image(fill_color="black", back_color="white")
                    
                    # 이미지 파일을 BytesIO 객체에 저장
                    image_buffer = BytesIO()
                    img.save(image_buffer, format='PNG')
                    image_buffer.seek(0)

                    # File 객체 생성
                    file_name = f"{student.name}_qr.png"  # 이미지 파일명 설정
                    file = File(image_buffer, name=file_name)

                    student.qr_code = file
                    student.save()
                    user = authenticate(username=username, password=password)
                    student.save()
                    
                    # 자동 로그인
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        login(request, user)
                        return render(request, 'home/home.html')
                    
                except ValidationError as validation_error:
                    messages.error(request, f"{validation_error}")
                    return render(request, 'user/student/signup.html', {'signup_form': signup_form, 'client_form': client_form})
                
    else:
        signup_form = SignUpForm()
        client_form = ClientForm()

    context = {
        'signup_form': signup_form, 
        'client_form': client_form,
        
        }
    
    return render(request, 'user/student/signup.html', context)


#  학생 정보
@login_required
def student_detail(request):
    user = User.objects.get(pk=request.user.pk)
    student = Student.objects.get(user_id=request.user.pk)
    division = Division.objects.get(pk=student.division_id)
    
    context = {
        'user': user,
        'student': student,
        'division': division,
    }

    return render(request, 'user/student/student_detail.html', context)
    
    
    
#  학생 정보 수정
@login_required
def edit_student(request):
    student = request.user.student

    if request.method == 'POST':
        form = StudentEditForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('user:student_detail')  # Replace 'profile' with the appropriate URL name for the profile page
    else:
        form = StudentEditForm(instance=student)

    return render(request, 'user/student/edit_student.html', {'form': form})


# 비밀번호 수정
@login_required
def edit_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeFormCustom(request.user, request.POST)

        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)

            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect('user:student_detail')  # Replace 'profile' with the appropriate URL name for the profile page
    else:
        password_form = PasswordChangeFormCustom(request.user)

    return render(request, 'user/student/edit_password.html', {'password_form': password_form})





## QR 코드 보여주기
# 입실    
@login_required
def show_in_qr(request):
    return render(request, 'user/student/show_in_qr.html')


# 퇴실    
@login_required
def show_out_qr(request):
    return render(request, 'user/student/show_out_qr.html')


########## 관리자 권한 필요 ################
## 분반
# 분반 목록
@user_passes_test(lambda u: u.is_staff, login_url='/') # 권한 없으면 홈으로
def division_list(request):
    divison = Division.objects.all()
    
    context = {'division': divison}
    return render(request, 'user/admin/admin_division_list.html', context)


# 분반 추가
@user_passes_test(lambda u: u.is_staff, login_url='/') # 권한 없으면 홈으로
def create_division(request):
    if request.method == 'POST':
        form = DivisionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:division_list')  # 적절한 URL로 리다이렉트

    else:
        form = DivisionForm()

    return render(request, 'user/admin/admin_create_division.html', {'form': form})



# 분반 수정
@user_passes_test(lambda u: u.is_staff, login_url='/') # 권한 없으면 홈으로
def edit_division(request, division_id):
    division = get_object_or_404(Division, pk=division_id)

    if request.method == 'POST':
        form = DivisionForm(request.POST, instance=division)
        if form.is_valid():
            form.save()
            return redirect('user:division_list')  # 적절한 URL로 리다이렉트

    else:
        form = DivisionForm(instance=division)

    return render(request, 'user/admin/admin_edit_division.html', {'form': form, 'division': division})



# 분반 삭제
@user_passes_test(lambda u: u.is_staff, login_url='/') # 권한 없으면 홈으로
def delete_division(request, division_id):
    division = get_object_or_404(Division, pk=division_id)
    
    if request.method == 'POST':
        try:
            division.delete()
            return redirect('user:division_list')  # 적절한 URL로 리다이렉트
        
        except ProtectedError:
            '''학생이 존재하는 분반을 지울시 생기는 오류'''
            
            # 해당 분반에 가입되어있는 학생 정보 전달
            users = User.objects.filter(student__division_id=division_id)
            
            context = {
                'users': users,
                
            }
            
            return render(request, 'user/error_page/division_protected_error.html', context)
    
    return render(request, 'user/admin/admin_delete_division.html', {'division': division})


# 학생 출석 정보
@login_required
def student_attendance_detail(request):
    student = request.user.student
    division = Division.objects.get(pk=student.division_id)
    course = Course.objects.filter(division_name_id=student.division_id)
    class_attend = ClassAttend.objects.filter(student_id_id=student.pk)
    


    context ={
        'student': student,
        'division': division,
        'course': course,
        'class_attend': class_attend,

    }

    return render(request, 'user/student/student_attendance_detail.html', context)



@login_required
def delete_student(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        user = authenticate(username=request.user.username, password=password)
        if user is not None:
            # 비밀번호가 맞는 경우 회원 삭제
            user.delete()
            return redirect('home')  # 회원탈퇴 후 리다이렉션할 URL
        else:
            # 비밀번호가 틀린 경우 에러 메시지 출력
            error_message = '비밀번호가 올바르지 않습니다.'
            return render(request, 'user/student/delete_student.html', {'error_message': error_message})
    else:
        return render(request, 'user/student/delete_student.html')

attendance_app/user/templates/user/admin/admin_create_division.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
</head>
<body>
  {% include 'home/navbar.html' %}
  <br><br><br>
    <div class="container">
      <a class="btn btn-danger" href="{% url 'user:division_list' %}" role="button">분반 목록으로</a>
      
      <br><br><br>
      
      <h1><b>분반 추가</b></h1>

      <br><br><br>      
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="row">
            <div class="col-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
            </div>
          </div>
          <br>
        {% endfor %}
  
        <button type="submit" class="btn btn-primary">분반 생성</button>
      </form>


  </div>
</body>
</html>

attendance_app/user/templates/user/admin/admin_delete_division.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
</head>
<body>
  {% include 'home/navbar.html' %}
  <br><br><br>
    <div class="container">
      <h1><b>분반 삭제</b></h1>

      <br><br><br>
      
      <p>정말로 삭제하시겠습니까? 해당 분반과 연결된 모든 학생들이 삭제됩니다!</p>
      <h3>{{ division.name }}</h3>
      
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제</button>
        <a href="{% url 'user:division_list' %}" class="btn btn-warning">취소</a>
      </form>


  </div>
</body>
</html>

attendance_app/user/templates/user/admin/admin_division_list.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
</head>
<body>
  {% include 'home/navbar.html' %}
  <br><br><br>
    <div class="container">
      <a class="btn btn-secondary" href="{% url 'user:admin_home' %}" role="button">관리자 페이지로</a>

      <br><br>

      <h1><b>전체 분반 목록</b></h1>

      <br><br><br>
      <a class="btn btn-primary" href="{% url 'user:create_division' %}" role="button">분반 추가</a>

      
      <br><br>
      <br><br><br>


      클릭하면 해당 분반의 강의 정보가 보여요

      <br><br>

      <ul class="list-group">
        {% for d in division %}

          <div class="row">
            <div class="col-9">
              <div class="list-group">
                <a href="{% url 'course:course_list' d.pk %}" class="list-group-item list-group-item-action">
                  {{ d }}
                </a>
              </div>

            </div>

            <div class="col-3">
              <a class="btn btn-info" href="{% url 'user:edit_division' d.pk %}" role="button">수정</a>
              <a class="btn btn-danger" href="{% url 'user:delete_division' d.pk %}" role="button">삭제</a>
            </div>
          </div>
          
          <br>
          
        {% endfor %}
      </ul>


  </div>
</body>
</html>

attendance_app/user/templates/user/admin/admin_edit_division.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
</head>
<body>
  {% include 'home/navbar.html' %}
  <br><br><br>
    <div class="container">
      <a class="btn btn-danger" href="{% url 'user:division_list' %}" role="button">분반 목록으로</a>
      
      <br><br><br>
      
      <h1><b>분반 수정</b></h1>

      <br><br><br>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">수정</button>
        <a class="btn btn-warning" href="{% url 'user:division_list' %}" role="button">취소</a>
      </form>


  </div>
</body>
</html>

attendance_app/user/templates/user/admin/admin_home.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
</head>
<body>
  {% include 'home/navbar.html' %}
  <br><br><br>
    <div class="container">
      <h1><b>관리자 페이지</b></h1>

      <br><br><br>
      
      <div class="list-group">
        <a href="{% url 'user:division_list' %}" class="list-group-item list-group-item-action">전체 분반/강의 목록</a>
      </div>

      <div class="list-group">
        <a href="{% url 'course:attendance_division_list' %}" class="list-group-item list-group-item-action">강의별 출석 현황</a>
      </div>

      <div class="list-group">
        <a href="{% url 'survey:survey_division_list' %}" class="list-group-item list-group-item-action">강의평가 조회</a>
      </div>


  </div>
</body>
</html>